baseurl = "https://leandro.ordonez.studio"
title = "Leandro Ordóñez Ante"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

googleAnalytics = "UA-149589206-1"

[params]
    author = "Leandro Ordóñez Ante"
    info = "PhD Researcher in Computer Sciences"
    description = "Leandro Ordóñez's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "Researching mechanisms for accessing large data in fast, efficient and reliable ways"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/LeandroOrdonez/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab fa-2x"
    weight = 2
    url = "https://gitlab.ilabt.imec.be/lordezan/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/OrdonezLeandro/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://linkedin.com/in/leandroordonez"
[[params.social]]
    name = "Stack Overflow"
    icon = "fab fa-stack-overflow fa-2x"
    weight = 3
    url = "https://stackoverflow.com/story/leandroordonez"

    

# Menu links
#[[menu.main]]
#    name = "Blog"
#    weight = 1
#    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"

# Language settings
[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            #[[languages.en.menu.main]]
            #name = "Blog"
            #weight = 2
            #url = "posts/"

    [languages.pt-br]
        languagename = "Español"

        [languages.pt-br.params]
            author = "Leandro Ordóñez Ante"
            info = "Estudiante de Doctorado en Ciencias de la Computación"
            description = "Sitio web personal del Leandro Ordóñez"
            keywords = "blog,desarrollador,personal"
            footercontent = "Investigo mecanismos para el acceso a Big Data de manera rápida, eficiente y confiable"

        [languages.pt-br.menu]

            [[languages.pt-br.menu.main]]
            name = "Sobre mi"
            weight = 1
            url = "about/"

            #[[languages.pt-br.menu.main]]
            #name = "Blog"
            #weight = 2
            #url = "posts/"