[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.127.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.127.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.127.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.127.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/phd/dissertation"
  to = "https://cloud.ilabt.imec.be/index.php/s/83jpXHMdsQ4Cem9"
  status = 301
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "https://ordonez.tech/*"
  to = "https://leandro.ordonez.tech/:splat"
  status = 301
  force = true
   
[[redirects]]
  from = "http://ordonez.tech/*"
  to = "https://leandro.ordonez.tech/:splat"
  status = 301
  force = true
